export const CREATE_LIST = 'CREATE_LIST';
export const DELETE_LIST = 'DELETE_LIST';

export const ADD_GROCERY = 'ADD_GROCERY';
export const DELETE_GROCERY = 'DELETE_GROCERY';
export const SET_GROCERY = 'CHECK_GROCERY';
export const SET_GROCERY_STORE = 'SET_GROCERY_STORE';

export const CREATE_STORE = 'CREATE_STORE';
export const DELETE_STORE = 'DELETE_STORE';

export const SET_CREATE_DIALOG = 'OPEN_CREATE_DIALOG';
export const SET_CREATE_STORE_DIALOG = 'SET_CREATE_STORE_DIALOG';
export const SET_LIST_DIALOG = 'SET_LIST_DIALOG';

export const SET_DARK_MODE = 'SET_DARK_MODE';